Fatal error: exception Failure("illegal actual argument in call to foo: found Tuple(Bool, Int), expected Int in TupleLit(BoolLit(False), IntLit(2))")
